POST http://localhost:3000/itens
content-type: application/json

{
    "id": 1,
    "nome": "Playstation",
    "preco": 1000,
    "estoque": 100,
    "categoria": "lazer"
}

###

GET http://localhost:3000/itens?categoria=tecnologia
content-type: application/json

### 
GET http://localhost:3000/itens
content-type: application/json
